### PR TITLE
Add wasmJs support

### PR DESCRIPTION
**Pull request by luca992**

### CODE REVIEW

**Review by ychescale9 — COMMENTED** [review]
Thanks for the contribution! are we able to move the dependency updates to a separate PR?

**Comment by luca992** [comment]
A few are needed. But I can revert anything strictly not needed if that works?

**Comment by ychescale9** [comment]
Sure. I don't mind merging coroutines RC as I'm not planning to publish a new release soon.

**Comment by luca992** [comment]
@ychescale9 coroutines and atomicfu had to be updated to support wasmJs. I reverted the rest and made another pr

**Pull request merged**
