### PR TITLE
Add KeyedSynchronizer for synchronized cache loader

### PR DESCRIPTION
**Pull request by dcvz**
Adds KeyedSynchronizer and tests to synchronize cache loader -- based on previous work by @ychescale9 .

### CODE REVIEW

**Comment by dcvz** [comment]
@ychescale9 looks like compilation was failing on JS due to test names. I've updated them now.

**Comment by dcvz** [comment]
Should also solve the concern in #14

**Comment by dcvz** [comment]
@ychescale9 Looks like detekt was failing, should be all green now 🤞

**Comment by ychescale9** [comment]
Thanks! Will take a look on the weekend.

**Comment by dcvz** [comment]
Thanks! Realized detekt was still catching something, checked it locally to verify now.

**Comment by ychescale9** [comment]
Thanks for contributing!

**Pull request merged**
